import React, { useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, Power, RefreshCw, TrendingDown } from "lucide-react";
import { api } from "./api";

const emptyState = {
  status: { mode: "UNKNOWN", exchange: "-", testnet: true, kill_switch: false },
  config: { risk: {}, strategies: {} },
  portfolio: { equity: null, peak_equity: null, drawdown: null, daily_pnl_pct: null, weekly_pnl_pct: null, gross_exposure: null, positions: [], events: [] },
};
const pct = (v) => (v == null ? "—" : `${(Number(v) * 100).toFixed(2)}%`);
const usd = (v) => (v == null ? "—" : Number(v).toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }));
function Gauge({ label, value, limit }) { const ratio = value == null || !limit ? 0 : Math.min(Math.abs(value) / limit, 1); return <div className="gauge"><div className="gauge-head"><span>{label}</span><b>{pct(value)} / {pct(limit)}</b></div><div className="track"><div className="fill" style={{ width: `${ratio * 100}%` }} /></div></div>; }

export default function Dashboard() {
  const [state, setState] = useState(emptyState); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [lastUpdated, setLastUpdated] = useState(null);
  const refresh = useCallback(async () => { try { const [status, config, portfolio] = await Promise.all([api.status(), api.config(), api.portfolio()]); setState({ status, config, portfolio }); setError(""); setLastUpdated(new Date()); } catch (err) { setError(err.message || "Backend unavailable"); } finally { setLoading(false); } }, []);
  useEffect(() => { refresh(); const id = setInterval(refresh, 5000); return () => clearInterval(id); }, [refresh]);
  const risk = state.config.risk || {}; const strategies = state.config.strategies || {}; const positions = state.portfolio.positions || []; const events = state.portfolio.events || {};
  const eventList = Array.isArray(events) ? events : [];
  return <main className="dash"><style>{`.dash{min-height:100vh;background:#0b0f14;color:#e7edf3;font:14px/1.45 Arial,sans-serif;padding:24px}.wrap{max-width:1200px;margin:auto}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.title{font-size:24px;font-weight:700}.muted{color:#8a97a6}.pill{padding:5px 10px;border:1px solid #3fb6a8;border-radius:20px;color:#3fb6a8;font-size:12px}.button{background:#121821;color:#e7edf3;border:1px solid #303b49;padding:9px 12px;border-radius:6px;cursor:pointer}.error{background:#35191a;border:1px solid #d6524a;color:#ff9b94;padding:12px;border-radius:6px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#121821;border:1px solid #232b36;border-radius:8px;padding:16px}.label{color:#8a97a6;font-size:11px;text-transform:uppercase;letter-spacing:.06em}.value{font-size:24px;font-weight:700;margin-top:5px}.section{margin-top:14px}.section h2{font-size:14px;text-transform:uppercase;color:#8a97a6;letter-spacing:.06em}.gauges{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.gauge-head{display:flex;justify-content:space-between;margin-bottom:7px;color:#8a97a6}.gauge-head b{color:#e7edf3}.track{height:7px;background:#232b36;border-radius:5px;overflow:hidden}.fill{height:100%;background:#3fb6a8;border-radius:5px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:10px;border-bottom:1px solid #232b36}.table th{color:#8a97a6;font-size:11px;text-transform:uppercase}.empty{padding:28px;text-align:center;color:#8a97a6;border:1px dashed #303b49;border-radius:6px}.danger{color:#d6524a}.safe{color:#3fb6a8}.footer{margin-top:20px;color:#5a6572;font-size:12px}@media(max-width:850px){.grid,.gauges{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.grid,.gauges{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}`}</style><div className="wrap">
  <div className="top"><div><div className="title">Adaptive Trading System</div><div className="muted">Live monitoring API · no simulated market data</div></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span className="pill">{state.status.mode}</span><button className="button" onClick={refresh}><RefreshCw size={15}/> Refresh</button></div></div>
  {error && <div className="error"><AlertTriangle size={16}/> {error}. Verify the FastAPI service and VITE_API_BASE_URL.</div>}
  <div className="grid"><div className="card"><div className="label">Backend</div><div className="value">{loading ? "…" : error ? "OFFLINE" : "ONLINE"}</div></div><div className="card"><div className="label">Exchange</div><div className="value">{state.status.exchange || "—"}</div></div><div className="card"><div className="label">Environment</div><div className="value">{state.status.testnet ? "TESTNET" : "LIVE"}</div></div><div className="card"><div className="label">Kill switch</div><div className={`value ${state.status.kill_switch ? "danger" : "safe"}`}><Power size={19}/> {state.status.kill_switch ? "TRIPPED" : "ARMED"}</div></div></div>
  <section className="section"><h2>Portfolio</h2><div className="grid"><div className="card"><div className="label">Equity</div><div className="value">{usd(state.portfolio.equity)}</div></div><div className="card"><div className="label">Daily P&L</div><div className="value">{pct(state.portfolio.daily_pnl_pct)}</div></div><div className="card"><div className="label">Weekly P&L</div><div className="value">{pct(state.portfolio.weekly_pnl_pct)}</div></div><div className="card"><div className="label">Gross exposure</div><div className="value">{pct(state.portfolio.gross_exposure)}</div></div></div></section>
  <section className="section"><h2>Risk limits</h2><div className="card"><div className="gauges"><Gauge label="Drawdown" value={state.portfolio.drawdown} limit={risk.max_drawdown_pct}/><Gauge label="Daily loss" value={state.portfolio.daily_pnl_pct == null ? null : Math.max(0,-state.portfolio.daily_pnl_pct)} limit={risk.daily_loss_limit_pct}/><Gauge label="Weekly loss" value={state.portfolio.weekly_pnl_pct == null ? null : Math.max(0,-state.portfolio.weekly_pnl_pct)} limit={risk.weekly_loss_limit_pct}/><Gauge label="Leverage" value={state.portfolio.gross_exposure} limit={risk.max_leverage}/></div></div></section>
  <section className="section"><h2>Positions</h2><div className="card">{positions.length ? <table className="table"><thead><tr><th>Asset</th><th>Weight</th><th>UPnL</th><th>Price</th></tr></thead><tbody>{positions.map((p,i)=><tr key={`${p.asset}-${i}`}><td>{p.asset}</td><td>{pct(p.weight)}</td><td>{pct(p.uPnlPct)}</td><td>{p.price ?? "—"}</td></tr>)}</tbody></table> : <div className="empty"><TrendingDown size={18}/> No positions are being reported by the backend.</div>}</div></section>
  <section className="section"><h2>Strategy configuration</h2><div className="card">{Object.keys(strategies).length ? Object.entries(strategies).map(([name,value])=><div key={name} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid #232b36"}}><span>{name}</span><span>{value && typeof value === "object" && "enabled" in value ? (value.enabled ? "enabled" : "disabled") : "configured"}</span></div>) : <div className="empty">No strategy metadata exposed.</div>}</div></section>
  <section className="section"><h2>Events</h2><div className="card">{eventList.length ? eventList.map((e,i)=><div key={i} style={{padding:"8px 0",borderBottom:"1px solid #232b36"}}>{e.text || JSON.stringify(e)}</div>) : <div className="empty"><Activity size={18}/> No events are being reported yet.</div>}</div></section>
  <div className="footer">{lastUpdated ? `Last API update: ${lastUpdated.toLocaleTimeString()}` : "Waiting for API"} · Read-only dashboard. Order placement is intentionally not exposed here.</div>
</div></main>;
}
